apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: default
  labels:
    app: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: ckwagaba/osprey-frontend:0.1.1
          ports:
            - containerPort: 3000
              name: react-frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: default
  labels:
    app: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: ckwagaba/osprey-backend:$COMMIT_SHA1
          ports:
            - containerPort: 5000
              name: flask-api
          env:
            - name: DATABASE_URI
              value: $DATABASE_URI
            - name: FLASK_APP_SECRET
              value: $FLASK_APP_SECRET
            - name: KUBE_HOST
              value: $KUBE_HOST
            - name: KUBE_TOKEN
              value: $KUBE_TOKEN
            - name: KUBE_CERT
              value: $KUBE_CERT
            - name: PROMETHEUS_URL
              value: $PROMETHEUS_URL
            - name: PROMETHEUS_HEAD
              value: $PROMETHEUS_HEAD

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: default
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:10.8-alpine
          ports:
            - containerPort: 5432
              name: postgres-db
          env:
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_DB
              value: osprey