apiVersion: v1
kind: Service
metadata:
  name: flask-api
  namespace: default
  labels:
    app: flask-api
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: flask-api
      name: flask-api
  selector:
    app: flask-api

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: default
  labels:
    app: postgres-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres-db
      name: postgres-db
  selector:
    app: postgres-db